before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install libavformat-dev
  - sudo apt-get -y install ffmpeg
  - cp config/secrets.yml.sample config/secrets.yml
  - rm config/database.yml
  - cp config/database.yml.travis config/database.yml
  - if [[ $DB == 'sqlite' ]]; then rm Gemfile.lock; fi
  - if [[ $DB == 'postgresql' ]]; then rm Gemfile.lock; fi
before_script:
  - cp config/redis.yml.sample config/redis.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
language: ruby
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
rvm:
  - 2.1.3
  - ruby-head
cache:
  - bundler
  - apt
addons:
   code_climate:
     repo_token: 1f90976d66c1c1cb114e5396479faf3be15c6656460bb6a87cd681a33fde210b
matrix:
  allow_failures:
    - rvm: ruby-head
